from __future__ import annotations

from typing import Any

DEFAULT_FASTER_WHISPER_CONFIG: dict[str, Any] = {
    "model": "small",
    "device": "auto",
    "device_index": 0,
    "compute_type": "auto",
    "language": None,
    "task": "transcribe",
    "beam_size": 5,
    "vad_filter": True,
    "vad_min_silence_ms": 500,
    "word_timestamps": False,
    "condition_on_previous_text": True,
    "cpu_threads": 0,
    "num_workers": 1,
    "keep_model_loaded": True,
    "realtime_chunk_seconds": 3.0,
    "realtime_overlap_seconds": 1.0,
}

FASTER_WHISPER_MODELS = (
    "tiny",
    "base",
    "small",
    "medium",
    "large-v3",
    "distil-large-v3",
    "turbo",
)

FASTER_WHISPER_MODEL_REPOSITORIES = {
    "tiny": "Systran/faster-whisper-tiny",
    "base": "Systran/faster-whisper-base",
    "small": "Systran/faster-whisper-small",
    "medium": "Systran/faster-whisper-medium",
    "large-v3": "Systran/faster-whisper-large-v3",
    "distil-large-v3": "Systran/faster-distil-whisper-large-v3",
    "turbo": "mobiuslabsgmbh/faster-whisper-large-v3-turbo",
}

COMPUTE_DEVICES = ("auto", "cpu", "cuda")

COMPUTE_TYPES = (
    "auto",
    "default",
    "int8",
    "int8_float32",
    "int8_float16",
    "int8_bfloat16",
    "int16",
    "float16",
    "bfloat16",
    "float32",
)

WHISPER_LANGUAGE_CODES = (
    "af",
    "am",
    "ar",
    "as",
    "az",
    "ba",
    "be",
    "bg",
    "bn",
    "bo",
    "br",
    "bs",
    "ca",
    "cs",
    "cy",
    "da",
    "de",
    "el",
    "en",
    "es",
    "et",
    "eu",
    "fa",
    "fi",
    "fo",
    "fr",
    "gl",
    "gu",
    "ha",
    "haw",
    "he",
    "hi",
    "hr",
    "ht",
    "hu",
    "hy",
    "id",
    "is",
    "it",
    "ja",
    "jw",
    "ka",
    "kk",
    "km",
    "kn",
    "ko",
    "la",
    "lb",
    "ln",
    "lo",
    "lt",
    "lv",
    "mg",
    "mi",
    "mk",
    "ml",
    "mn",
    "mr",
    "ms",
    "mt",
    "my",
    "ne",
    "nl",
    "nn",
    "no",
    "oc",
    "pa",
    "pl",
    "ps",
    "pt",
    "ro",
    "ru",
    "sa",
    "sd",
    "si",
    "sk",
    "sl",
    "sn",
    "so",
    "sq",
    "sr",
    "su",
    "sv",
    "sw",
    "ta",
    "te",
    "tg",
    "th",
    "tk",
    "tl",
    "tr",
    "tt",
    "uk",
    "ur",
    "uz",
    "vi",
    "yi",
    "yo",
    "zh",
    "yue",
)


def faster_whisper_config(preferences: dict[str, Any]) -> dict[str, Any]:
    stored = preferences.get("faster_whisper")
    values = stored if isinstance(stored, dict) else {}
    return {**DEFAULT_FASTER_WHISPER_CONFIG, **values}
